[package]
name = "primes_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
is_prime = "2.0.9"
num = { version = "0.4.1", features = ["rand"] }
rand = "0.8.5"
